# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dict_gui.ui'
#
# Created: Wed Mar 19 12:40:11 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DictLearn(object):
    def setupUi(self, DictLearn):
        DictLearn.setObjectName(_fromUtf8("DictLearn"))
        DictLearn.resize(607, 563)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DictLearn.sizePolicy().hasHeightForWidth())
        DictLearn.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(DictLearn)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.Word_box = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Word_box.sizePolicy().hasHeightForWidth())
        self.Word_box.setSizePolicy(sizePolicy)
        self.Word_box.setTitle(_fromUtf8(""))
        self.Word_box.setObjectName(_fromUtf8("Word_box"))
        self.wcount = QtGui.QLabel(self.Word_box)
        self.wcount.setGeometry(QtCore.QRect(30, 30, 120, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wcount.sizePolicy().hasHeightForWidth())
        self.wcount.setSizePolicy(sizePolicy)
        self.wcount.setMinimumSize(QtCore.QSize(120, 0))
        self.wcount.setObjectName(_fromUtf8("wcount"))
        self.word_count = QtGui.QSpinBox(self.Word_box)
        self.word_count.setGeometry(QtCore.QRect(180, 20, 55, 27))
        self.word_count.setObjectName(_fromUtf8("word_count"))
        self.horizontalLayout.addWidget(self.Word_box)
        self.info = QtGui.QLabel(self.frame)
        self.info.setText(_fromUtf8(""))
        self.info.setObjectName(_fromUtf8("info"))
        self.horizontalLayout.addWidget(self.info)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 2)
        self.buttonFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFrame.sizePolicy().hasHeightForWidth())
        self.buttonFrame.setSizePolicy(sizePolicy)
        self.buttonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonFrame.setObjectName(_fromUtf8("buttonFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Vocabulary = QtGui.QPushButton(self.buttonFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Vocabulary.setPalette(palette)
        self.Vocabulary.setObjectName(_fromUtf8("Vocabulary"))
        self.horizontalLayout_4.addWidget(self.Vocabulary)
        self.Texts = QtGui.QPushButton(self.buttonFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Texts.setPalette(palette)
        self.Texts.setObjectName(_fromUtf8("Texts"))
        self.horizontalLayout_4.addWidget(self.Texts)
        self.Texts2 = QtGui.QPushButton(self.buttonFrame)
        self.Texts2.setObjectName(_fromUtf8("Texts2"))
        self.horizontalLayout_4.addWidget(self.Texts2)
        self.gridLayout.addWidget(self.buttonFrame, 2, 0, 1, 1)
        DictLearn.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DictLearn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        DictLearn.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DictLearn)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DictLearn.setStatusBar(self.statusbar)
        self.dockConsole = QtGui.QDockWidget(DictLearn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockConsole.sizePolicy().hasHeightForWidth())
        self.dockConsole.setSizePolicy(sizePolicy)
        self.dockConsole.setObjectName(_fromUtf8("dockConsole"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame1 = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.consLabel = QtGui.QLabel(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consLabel.sizePolicy().hasHeightForWidth())
        self.consLabel.setSizePolicy(sizePolicy)
        self.consLabel.setObjectName(_fromUtf8("consLabel"))
        self.horizontalLayout_5.addWidget(self.consLabel)
        self.Clear = QtGui.QPushButton(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear.sizePolicy().hasHeightForWidth())
        self.Clear.setSizePolicy(sizePolicy)
        self.Clear.setObjectName(_fromUtf8("Clear"))
        self.horizontalLayout_5.addWidget(self.Clear)
        self.verticalLayout_2.addWidget(self.frame1)
        self.console = QtGui.QTextEdit(self.dockWidgetContents)
        self.console.setReadOnly(True)
        self.console.setObjectName(_fromUtf8("console"))
        self.verticalLayout_2.addWidget(self.console)
        self.dockConsole.setWidget(self.dockWidgetContents)
        DictLearn.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockConsole)
        self.actionLearn = QtGui.QAction(DictLearn)
        self.actionLearn.setEnabled(False)
        self.actionLearn.setObjectName(_fromUtf8("actionLearn"))
        self.actionDecomp = QtGui.QAction(DictLearn)
        self.actionDecomp.setEnabled(False)
        self.actionDecomp.setObjectName(_fromUtf8("actionDecomp"))
        self.actionView_dict = QtGui.QAction(DictLearn)
        self.actionView_dict.setEnabled(False)
        self.actionView_dict.setObjectName(_fromUtf8("actionView_dict"))
        self.actionView_decomp = QtGui.QAction(DictLearn)
        self.actionView_decomp.setEnabled(False)
        self.actionView_decomp.setObjectName(_fromUtf8("actionView_decomp"))
        self.actionHide_console = QtGui.QAction(DictLearn)
        self.actionHide_console.setObjectName(_fromUtf8("actionHide_console"))
        self.actionQuit = QtGui.QAction(DictLearn)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionDict_params = QtGui.QAction(DictLearn)
        self.actionDict_params.setObjectName(_fromUtf8("actionDict_params"))
        self.actionView_options = QtGui.QAction(DictLearn)
        self.actionView_options.setObjectName(_fromUtf8("actionView_options"))
        self.actionLoad = QtGui.QAction(DictLearn)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionDump = QtGui.QAction(DictLearn)
        self.actionDump.setObjectName(_fromUtf8("actionDump"))
        self.menuFile.addAction(self.actionLearn)
        self.menuFile.addAction(self.actionDecomp)
        self.menuFile.addAction(self.actionView_dict)
        self.menuFile.addAction(self.actionView_decomp)
        self.menuFile.addAction(self.actionHide_console)
        self.menuFile.addAction(self.actionDump)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionQuit)
        self.menuPreferences.addAction(self.actionDict_params)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(DictLearn)
        QtCore.QMetaObject.connectSlotsByName(DictLearn)

    def retranslateUi(self, DictLearn):
        DictLearn.setWindowTitle(QtGui.QApplication.translate("DictLearn", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("DictLearn", "choosethe dictionary structure (no default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("DictLearn", "choose dictionary structure", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("DictLearn", "unstructured", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("DictLearn", "graph struct", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("DictLearn", "tree struct", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("DictLearn", "symetric tree", None, QtGui.QApplication.UnicodeUTF8))
        self.wcount.setText(QtGui.QApplication.translate("DictLearn", "nb words to show:", None, QtGui.QApplication.UnicodeUTF8))
        self.Vocabulary.setToolTip(QtGui.QApplication.translate("DictLearn", "select file containing the vocabulary", None, QtGui.QApplication.UnicodeUTF8))
        self.Vocabulary.setText(QtGui.QApplication.translate("DictLearn", "Vocabulary", None, QtGui.QApplication.UnicodeUTF8))
        self.Texts.setToolTip(QtGui.QApplication.translate("DictLearn", "data files for dictionary learning", None, QtGui.QApplication.UnicodeUTF8))
        self.Texts.setStatusTip(QtGui.QApplication.translate("DictLearn", "choose  files", None, QtGui.QApplication.UnicodeUTF8))
        self.Texts.setText(QtGui.QApplication.translate("DictLearn", "Texts for training", None, QtGui.QApplication.UnicodeUTF8))
        self.Texts2.setToolTip(QtGui.QApplication.translate("DictLearn", "texts to decompose on the learnt dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.Texts2.setText(QtGui.QApplication.translate("DictLearn", "Texts to decompose", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DictLearn", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferences.setTitle(QtGui.QApplication.translate("DictLearn", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.consLabel.setText(QtGui.QApplication.translate("DictLearn", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.Clear.setText(QtGui.QApplication.translate("DictLearn", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLearn.setText(QtGui.QApplication.translate("DictLearn", "Learn dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecomp.setText(QtGui.QApplication.translate("DictLearn", "Compute decomposition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_dict.setText(QtGui.QApplication.translate("DictLearn", "View dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_decomp.setText(QtGui.QApplication.translate("DictLearn", "View decomposition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_console.setText(QtGui.QApplication.translate("DictLearn", "Hide console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DictLearn", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDict_params.setText(QtGui.QApplication.translate("DictLearn", "dictionary params", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_options.setText(QtGui.QApplication.translate("DictLearn", "visualisation options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("DictLearn", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDump.setText(QtGui.QApplication.translate("DictLearn", "Dump", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DictLearn = QtGui.QMainWindow()
    ui = Ui_DictLearn()
    ui.setupUi(DictLearn)
    DictLearn.show()
    sys.exit(app.exec_())

