/* Generated by Cython 3.0.12 */

#ifndef __PYX_HAVE__cython_blas_lapack
#define __PYX_HAVE__cython_blas_lapack

#include "Python.h"

#ifndef __PYX_HAVE_API__cython_blas_lapack

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double dnrm2_(int *, double *, int *);
__PYX_EXTERN_C float snrm2_(int *, float *, int *);
__PYX_EXTERN_C void dcopy_(int *, double *, int *, double *, int *);
__PYX_EXTERN_C void scopy_(int *, float *, int *, float *, int *);
__PYX_EXTERN_C void daxpy_(int *, double *, double *, int *, double *, int *);
__PYX_EXTERN_C void saxpy_(int *, float *, float *, int *, float *, int *);
__PYX_EXTERN_C void dscal_(int *, double *, double *, int *);
__PYX_EXTERN_C void sscal_(int *, float *, float *, int *);
__PYX_EXTERN_C double dasum_(int *, double *, int *);
__PYX_EXTERN_C float sasum_(int *, float *, int *);
__PYX_EXTERN_C double ddot_(int *, double *, int *, double *, int *);
__PYX_EXTERN_C float sdot_(int *, float *, int *, float *, int *);
__PYX_EXTERN_C void dgemv_(char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
__PYX_EXTERN_C void sgemv_(char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
__PYX_EXTERN_C void dger_(int *, int *, double *, double *, int *, double *, int *, double *, int *);
__PYX_EXTERN_C void sger_(int *, int *, float *, float *, int *, float *, int *, float *, int *);
__PYX_EXTERN_C void dtrmv_(char *, char *, char *, int *, double *, int *, double *, int *);
__PYX_EXTERN_C void strmv_(char *, char *, char *, int *, float *, int *, float *, int *);
__PYX_EXTERN_C void dsyr_(char *, int *, double *, double *, int *, double *, int *);
__PYX_EXTERN_C void ssyr_(char *, int *, float *, float *, int *, float *, int *);
__PYX_EXTERN_C void dsymv_(char *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
__PYX_EXTERN_C void ssymv_(char *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
__PYX_EXTERN_C void dgemm_(char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
__PYX_EXTERN_C void sgemm_(char *, char *, int *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
__PYX_EXTERN_C void dsyrk_(char *, char *, int *, int *, double *, double *, int *, double *, double *, int *);
__PYX_EXTERN_C void ssyrk_(char *, char *, int *, int *, float *, float *, int *, float *, float *, int *);
__PYX_EXTERN_C void dtrmm_(char *, char *, char *, char *, int *, int *, double *, double *, int *, double *, int *);
__PYX_EXTERN_C void strmm_(char *, char *, char *, char *, int *, int *, float *, float *, int *, float *, int *);
__PYX_EXTERN_C int idamax_(int *, double *, int *);
__PYX_EXTERN_C int isamax_(int *, float *, int *);
__PYX_EXTERN_C void dtrtri_(char *, char *, int *, double *, int *, int *);
__PYX_EXTERN_C void strtri_(char *, char *, int *, float *, int *, int *);
__PYX_EXTERN_C void dsytrf_(char *, int *, double *, int *, int *, double *, int *, int *);
__PYX_EXTERN_C void ssytrf_(char *, int *, float *, int *, int *, float *, int *, int *);
__PYX_EXTERN_C void dsytri_(char *, int *, double *, int *, int *, double *, int *);
__PYX_EXTERN_C void ssytri_(char *, int *, float *, int *, int *, float *, int *);
__PYX_EXTERN_C void dlasrt_(char *, int *, double *, int *);
__PYX_EXTERN_C void slasrt_(char *, int *, float *, int *);
__PYX_EXTERN_C void dgesvd_(char *, char *, int *, int *, double *, int *, double *, double *, int *, double *, int *, double *, int *, int *);
__PYX_EXTERN_C void sgesvd_(char *, char *, int *, int *, float *, int *, float *, float *, int *, float *, int *, float *, int *, int *);
__PYX_EXTERN_C void dsyev_(char *, char *, int *, double *, int *, double *, double *, int *, int *);
__PYX_EXTERN_C void ssyev_(char *, char *, int *, float *, int *, float *, float *, int *, int *);

#endif /* !__PYX_HAVE_API__cython_blas_lapack */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcython_blas_lapack(void);
#else
/* WARNING: Use PyImport_AppendInittab("cython_blas_lapack", PyInit_cython_blas_lapack) instead of calling PyInit_cython_blas_lapack directly from Python 3.5 */
PyMODINIT_FUNC PyInit_cython_blas_lapack(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"cython_blas_lapack\", PyInit_cython_blas_lapack) instead of calling PyInit_cython_blas_lapack directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"cython_blas_lapack\", PyInit_cython_blas_lapack) instead of calling PyInit_cython_blas_lapack directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"cython_blas_lapack\", PyInit_cython_blas_lapack) instead of calling PyInit_cython_blas_lapack directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_cython_blas_lapack_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_cython_blas_lapack() __PYX_WARN_IF_PyInit_cython_blas_lapack_INIT_CALLED(PyInit_cython_blas_lapack())
#endif
#endif

#endif /* !__PYX_HAVE__cython_blas_lapack */
