[build-system]
requires = ["oldest-supported-numpy",
            "setuptools",
            "distro",
            "wheel",
            "mkl;platform_system=='Windows'",
            "mkl-devel;platform_system=='Windows'",
            "mkl-include;platform_system=='Windows'"]
