# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dparams_gui.ui'
#
# Created: Wed Mar 19 12:40:11 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ParamWindow(object):
    def setupUi(self, ParamWindow):
        ParamWindow.setObjectName(_fromUtf8("ParamWindow"))
        ParamWindow.resize(591, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParamWindow.sizePolicy().hasHeightForWidth())
        ParamWindow.setSizePolicy(sizePolicy)
        ParamWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(ParamWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.headFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headFrame.sizePolicy().hasHeightForWidth())
        self.headFrame.setSizePolicy(sizePolicy)
        self.headFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.headFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.headFrame.setObjectName(_fromUtf8("headFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.headFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.modeInfo = QtGui.QLabel(self.headFrame)
        self.modeInfo.setObjectName(_fromUtf8("modeInfo"))
        self.horizontalLayout.addWidget(self.modeInfo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Reset = QtGui.QPushButton(self.headFrame)
        self.Reset.setObjectName(_fromUtf8("Reset"))
        self.horizontalLayout.addWidget(self.Reset)
        self.Close = QtGui.QPushButton(self.headFrame)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.horizontalLayout.addWidget(self.Close)
        self.verticalLayout.addWidget(self.headFrame)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.ptabWidget = QtGui.QTabWidget(self.centralwidget)
        self.ptabWidget.setObjectName(_fromUtf8("ptabWidget"))
        self.unstructTab = QtGui.QWidget()
        self.unstructTab.setObjectName(_fromUtf8("unstructTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.unstructTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_u1 = QtGui.QGroupBox(self.unstructTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_u1.sizePolicy().hasHeightForWidth())
        self.groupBox_u1.setSizePolicy(sizePolicy)
        self.groupBox_u1.setObjectName(_fromUtf8("groupBox_u1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_u1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lambda1_u = QtGui.QLabel(self.groupBox_u1)
        self.lambda1_u.setObjectName(_fromUtf8("lambda1_u"))
        self.horizontalLayout_4.addWidget(self.lambda1_u)
        self.lambdaEdit_u = QtGui.QLineEdit(self.groupBox_u1)
        self.lambdaEdit_u.setObjectName(_fromUtf8("lambdaEdit_u"))
        self.horizontalLayout_4.addWidget(self.lambdaEdit_u)
        self.verticalLayout_4.addWidget(self.groupBox_u1)
        self.groupBox_u2 = QtGui.QGroupBox(self.unstructTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_u2.sizePolicy().hasHeightForWidth())
        self.groupBox_u2.setSizePolicy(sizePolicy)
        self.groupBox_u2.setObjectName(_fromUtf8("groupBox_u2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_u2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gamma1_u = QtGui.QLabel(self.groupBox_u2)
        self.gamma1_u.setObjectName(_fromUtf8("gamma1_u"))
        self.horizontalLayout_5.addWidget(self.gamma1_u)
        self.gamma1Edit_u = QtGui.QLineEdit(self.groupBox_u2)
        self.gamma1Edit_u.setObjectName(_fromUtf8("gamma1Edit_u"))
        self.horizontalLayout_5.addWidget(self.gamma1Edit_u)
        self.verticalLayout_4.addWidget(self.groupBox_u2)
        self.regulFrame_u = QtGui.QFrame(self.unstructTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulFrame_u.sizePolicy().hasHeightForWidth())
        self.regulFrame_u.setSizePolicy(sizePolicy)
        self.regulFrame_u.setObjectName(_fromUtf8("regulFrame_u"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.regulFrame_u)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.regul_u = QtGui.QLabel(self.regulFrame_u)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regul_u.sizePolicy().hasHeightForWidth())
        self.regul_u.setSizePolicy(sizePolicy)
        self.regul_u.setObjectName(_fromUtf8("regul_u"))
        self.horizontalLayout_2.addWidget(self.regul_u)
        self.regulBox_u = QtGui.QComboBox(self.regulFrame_u)
        self.regulBox_u.setObjectName(_fromUtf8("regulBox_u"))
        self.regulBox_u.addItem(_fromUtf8(""))
        self.regulBox_u.addItem(_fromUtf8(""))
        self.regulBox_u.addItem(_fromUtf8(""))
        self.regulBox_u.addItem(_fromUtf8(""))
        self.regulBox_u.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.regulBox_u)
        self.verticalLayout_4.addWidget(self.regulFrame_u)
        self.ptabWidget.addTab(self.unstructTab, _fromUtf8(""))
        self.graphTab = QtGui.QWidget()
        self.graphTab.setObjectName(_fromUtf8("graphTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.graphTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_g1 = QtGui.QGroupBox(self.graphTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_g1.sizePolicy().hasHeightForWidth())
        self.groupBox_g1.setSizePolicy(sizePolicy)
        self.groupBox_g1.setObjectName(_fromUtf8("groupBox_g1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_g1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lambda1_g = QtGui.QLabel(self.groupBox_g1)
        self.lambda1_g.setObjectName(_fromUtf8("lambda1_g"))
        self.horizontalLayout_6.addWidget(self.lambda1_g)
        self.lambdaEdit_g = QtGui.QLineEdit(self.groupBox_g1)
        self.lambdaEdit_g.setObjectName(_fromUtf8("lambdaEdit_g"))
        self.horizontalLayout_6.addWidget(self.lambdaEdit_g)
        self.verticalLayout_5.addWidget(self.groupBox_g1)
        self.groupBox_g2 = QtGui.QGroupBox(self.graphTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_g2.sizePolicy().hasHeightForWidth())
        self.groupBox_g2.setSizePolicy(sizePolicy)
        self.groupBox_g2.setObjectName(_fromUtf8("groupBox_g2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_g2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gamma1_g = QtGui.QLabel(self.groupBox_g2)
        self.gamma1_g.setObjectName(_fromUtf8("gamma1_g"))
        self.horizontalLayout_7.addWidget(self.gamma1_g)
        self.gamma1Edit_g = QtGui.QLineEdit(self.groupBox_g2)
        self.gamma1Edit_g.setObjectName(_fromUtf8("gamma1Edit_g"))
        self.horizontalLayout_7.addWidget(self.gamma1Edit_g)
        self.verticalLayout_5.addWidget(self.groupBox_g2)
        self.regulFrame_g = QtGui.QFrame(self.graphTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulFrame_g.sizePolicy().hasHeightForWidth())
        self.regulFrame_g.setSizePolicy(sizePolicy)
        self.regulFrame_g.setFrameShape(QtGui.QFrame.StyledPanel)
        self.regulFrame_g.setFrameShadow(QtGui.QFrame.Raised)
        self.regulFrame_g.setObjectName(_fromUtf8("regulFrame_g"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.regulFrame_g)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.regul_g = QtGui.QLabel(self.regulFrame_g)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regul_g.sizePolicy().hasHeightForWidth())
        self.regul_g.setSizePolicy(sizePolicy)
        self.regul_g.setObjectName(_fromUtf8("regul_g"))
        self.horizontalLayout_8.addWidget(self.regul_g)
        self.regulBox_g = QtGui.QComboBox(self.regulFrame_g)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulBox_g.sizePolicy().hasHeightForWidth())
        self.regulBox_g.setSizePolicy(sizePolicy)
        self.regulBox_g.setObjectName(_fromUtf8("regulBox_g"))
        self.regulBox_g.addItem(_fromUtf8(""))
        self.regulBox_g.addItem(_fromUtf8(""))
        self.regulBox_g.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.regulBox_g)
        self.verticalLayout_5.addWidget(self.regulFrame_g)
        self.ptabWidget.addTab(self.graphTab, _fromUtf8(""))
        self.treeTab = QtGui.QWidget()
        self.treeTab.setObjectName(_fromUtf8("treeTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.treeTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_t1 = QtGui.QGroupBox(self.treeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_t1.sizePolicy().hasHeightForWidth())
        self.groupBox_t1.setSizePolicy(sizePolicy)
        self.groupBox_t1.setObjectName(_fromUtf8("groupBox_t1"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_t1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lambda1_t = QtGui.QLabel(self.groupBox_t1)
        self.lambda1_t.setObjectName(_fromUtf8("lambda1_t"))
        self.horizontalLayout_10.addWidget(self.lambda1_t)
        self.lambdaEdit_t = QtGui.QLineEdit(self.groupBox_t1)
        self.lambdaEdit_t.setObjectName(_fromUtf8("lambdaEdit_t"))
        self.horizontalLayout_10.addWidget(self.lambdaEdit_t)
        self.verticalLayout_8.addWidget(self.groupBox_t1)
        self.groupBox_t2 = QtGui.QGroupBox(self.treeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_t2.sizePolicy().hasHeightForWidth())
        self.groupBox_t2.setSizePolicy(sizePolicy)
        self.groupBox_t2.setObjectName(_fromUtf8("groupBox_t2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_t2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gamma1_t = QtGui.QLabel(self.groupBox_t2)
        self.gamma1_t.setObjectName(_fromUtf8("gamma1_t"))
        self.horizontalLayout_11.addWidget(self.gamma1_t)
        self.gamma1Edit_t = QtGui.QLineEdit(self.groupBox_t2)
        self.gamma1Edit_t.setObjectName(_fromUtf8("gamma1Edit_t"))
        self.horizontalLayout_11.addWidget(self.gamma1Edit_t)
        self.verticalLayout_8.addWidget(self.groupBox_t2)
        self.regulFrame_t = QtGui.QFrame(self.treeTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulFrame_t.sizePolicy().hasHeightForWidth())
        self.regulFrame_t.setSizePolicy(sizePolicy)
        self.regulFrame_t.setFrameShape(QtGui.QFrame.StyledPanel)
        self.regulFrame_t.setFrameShadow(QtGui.QFrame.Raised)
        self.regulFrame_t.setObjectName(_fromUtf8("regulFrame_t"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.regulFrame_t)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.regul_t = QtGui.QLabel(self.regulFrame_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regul_t.sizePolicy().hasHeightForWidth())
        self.regul_t.setSizePolicy(sizePolicy)
        self.regul_t.setObjectName(_fromUtf8("regul_t"))
        self.horizontalLayout_3.addWidget(self.regul_t)
        self.regulBox_t = QtGui.QComboBox(self.regulFrame_t)
        self.regulBox_t.setObjectName(_fromUtf8("regulBox_t"))
        self.regulBox_t.addItem(_fromUtf8(""))
        self.regulBox_t.addItem(_fromUtf8(""))
        self.regulBox_t.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.regulBox_t)
        self.verticalLayout_8.addWidget(self.regulFrame_t)
        self.ptabWidget.addTab(self.treeTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.ptabWidget)
        self.advancedParams = QtGui.QPushButton(self.centralwidget)
        self.advancedParams.setObjectName(_fromUtf8("advancedParams"))
        self.verticalLayout.addWidget(self.advancedParams)
        self.advancedFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedFrame.sizePolicy().hasHeightForWidth())
        self.advancedFrame.setSizePolicy(sizePolicy)
        self.advancedFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.advancedFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.advancedFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.advancedFrame.setObjectName(_fromUtf8("advancedFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.advancedFrame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.advBox1 = QtGui.QGroupBox(self.advancedFrame)
        self.advBox1.setTitle(_fromUtf8(""))
        self.advBox1.setObjectName(_fromUtf8("advBox1"))
        self.gridLayout = QtGui.QGridLayout(self.advBox1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.numthrEdit = QtGui.QLineEdit(self.advBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numthrEdit.sizePolicy().hasHeightForWidth())
        self.numthrEdit.setSizePolicy(sizePolicy)
        self.numthrEdit.setObjectName(_fromUtf8("numthrEdit"))
        self.gridLayout.addWidget(self.numthrEdit, 0, 1, 1, 1)
        self.iterEdit = QtGui.QLineEdit(self.advBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iterEdit.sizePolicy().hasHeightForWidth())
        self.iterEdit.setSizePolicy(sizePolicy)
        self.iterEdit.setObjectName(_fromUtf8("iterEdit"))
        self.gridLayout.addWidget(self.iterEdit, 0, 5, 1, 1)
        self.batchEdit = QtGui.QLineEdit(self.advBox1)
        self.batchEdit.setObjectName(_fromUtf8("batchEdit"))
        self.gridLayout.addWidget(self.batchEdit, 1, 1, 1, 1)
        self.Batchsize = QtGui.QLabel(self.advBox1)
        self.Batchsize.setObjectName(_fromUtf8("Batchsize"))
        self.gridLayout.addWidget(self.Batchsize, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.tolEdit = QtGui.QLineEdit(self.advBox1)
        self.tolEdit.setObjectName(_fromUtf8("tolEdit"))
        self.gridLayout.addWidget(self.tolEdit, 1, 5, 1, 1)
        self.Tol = QtGui.QLabel(self.advBox1)
        self.Tol.setObjectName(_fromUtf8("Tol"))
        self.gridLayout.addWidget(self.Tol, 1, 4, 1, 1)
        self.Iter = QtGui.QLabel(self.advBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Iter.sizePolicy().hasHeightForWidth())
        self.Iter.setSizePolicy(sizePolicy)
        self.Iter.setObjectName(_fromUtf8("Iter"))
        self.gridLayout.addWidget(self.Iter, 0, 4, 1, 1)
        self.Numthr = QtGui.QLabel(self.advBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Numthr.sizePolicy().hasHeightForWidth())
        self.Numthr.setSizePolicy(sizePolicy)
        self.Numthr.setObjectName(_fromUtf8("Numthr"))
        self.gridLayout.addWidget(self.Numthr, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.advBox1)
        self.verticalLayout.addWidget(self.advancedFrame)
        ParamWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ParamWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ParamWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ParamWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ParamWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ParamWindow)
        self.ptabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ParamWindow)

    def retranslateUi(self, ParamWindow):
        ParamWindow.setWindowTitle(QtGui.QApplication.translate("ParamWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.modeInfo.setText(QtGui.QApplication.translate("ParamWindow", "Current mode: Unstructured", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setToolTip(QtGui.QApplication.translate("ParamWindow", "reset parameters to default values", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setText(QtGui.QApplication.translate("ParamWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("ParamWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lambda1_u.setText(QtGui.QApplication.translate("ParamWindow", "lambda", None, QtGui.QApplication.UnicodeUTF8))
        self.lambdaEdit_u.setText(QtGui.QApplication.translate("ParamWindow", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1_u.setText(QtGui.QApplication.translate("ParamWindow", "gamma1", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1Edit_u.setText(QtGui.QApplication.translate("ParamWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.regul_u.setText(QtGui.QApplication.translate("ParamWindow", "regularization type:", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_u.setItemText(0, QtGui.QApplication.translate("ParamWindow", "elastic-net", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_u.setItemText(1, QtGui.QApplication.translate("ParamWindow", "l2", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_u.setItemText(2, QtGui.QApplication.translate("ParamWindow", "l0", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_u.setItemText(3, QtGui.QApplication.translate("ParamWindow", "linf", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_u.setItemText(4, QtGui.QApplication.translate("ParamWindow", "ridge", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.unstructTab), QtGui.QApplication.translate("ParamWindow", "Unstructured mode", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabToolTip(self.ptabWidget.indexOf(self.unstructTab), QtGui.QApplication.translate("ParamWindow", "params for unstructured dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.lambda1_g.setText(QtGui.QApplication.translate("ParamWindow", "lambda", None, QtGui.QApplication.UnicodeUTF8))
        self.lambdaEdit_g.setText(QtGui.QApplication.translate("ParamWindow", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1_g.setText(QtGui.QApplication.translate("ParamWindow", "gamma1", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1Edit_g.setText(QtGui.QApplication.translate("ParamWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.regul_g.setText(QtGui.QApplication.translate("ParamWindow", "regularization type:", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_g.setItemText(0, QtGui.QApplication.translate("ParamWindow", "graph", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_g.setItemText(1, QtGui.QApplication.translate("ParamWindow", "graph-l2", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_g.setItemText(2, QtGui.QApplication.translate("ParamWindow", "graph-ridge", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.graphTab), QtGui.QApplication.translate("ParamWindow", "Graph mode", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabToolTip(self.ptabWidget.indexOf(self.graphTab), QtGui.QApplication.translate("ParamWindow", "params for dictionary with graph structure", None, QtGui.QApplication.UnicodeUTF8))
        self.lambda1_t.setText(QtGui.QApplication.translate("ParamWindow", "lambda", None, QtGui.QApplication.UnicodeUTF8))
        self.lambdaEdit_t.setText(QtGui.QApplication.translate("ParamWindow", "0.0001", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1_t.setText(QtGui.QApplication.translate("ParamWindow", "gamma1", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma1Edit_t.setText(QtGui.QApplication.translate("ParamWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.regul_t.setText(QtGui.QApplication.translate("ParamWindow", "regularization type:", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_t.setItemText(0, QtGui.QApplication.translate("ParamWindow", "tree-l2", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_t.setItemText(1, QtGui.QApplication.translate("ParamWindow", "tree-l0", None, QtGui.QApplication.UnicodeUTF8))
        self.regulBox_t.setItemText(2, QtGui.QApplication.translate("ParamWindow", "tree-linf", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.treeTab), QtGui.QApplication.translate("ParamWindow", "Tree mode", None, QtGui.QApplication.UnicodeUTF8))
        self.ptabWidget.setTabToolTip(self.ptabWidget.indexOf(self.treeTab), QtGui.QApplication.translate("ParamWindow", "params for dictionary with tree structure", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedParams.setToolTip(QtGui.QApplication.translate("ParamWindow", "show/hide  advanced parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedParams.setText(QtGui.QApplication.translate("ParamWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.numthrEdit.setText(QtGui.QApplication.translate("ParamWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.iterEdit.setText(QtGui.QApplication.translate("ParamWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.batchEdit.setText(QtGui.QApplication.translate("ParamWindow", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.Batchsize.setText(QtGui.QApplication.translate("ParamWindow", "batch size :", None, QtGui.QApplication.UnicodeUTF8))
        self.tolEdit.setText(QtGui.QApplication.translate("ParamWindow", "1.e-3", None, QtGui.QApplication.UnicodeUTF8))
        self.Tol.setText(QtGui.QApplication.translate("ParamWindow", "tol :", None, QtGui.QApplication.UnicodeUTF8))
        self.Iter.setText(QtGui.QApplication.translate("ParamWindow", "nb iterations :", None, QtGui.QApplication.UnicodeUTF8))
        self.Numthr.setText(QtGui.QApplication.translate("ParamWindow", "nb cpus :", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ParamWindow = QtGui.QMainWindow()
    ui = Ui_ParamWindow()
    ui.setupUi(ParamWindow)
    ParamWindow.show()
    sys.exit(app.exec_())

